{
 "title": "Ark",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Number of failed backups in past 24h",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(ark_backup_failure_total[24h]))"
    }
   ]
  },
  {
   "title": "Number of successful backups in past 24h",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(ark_backup_success_total[24h]))"
    }
   ]
  },
  { "title": "Ark metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Number of backups per schedule",
   "type": "graph",
   "description": "Shows counter values. So only number of backups from last ark server restart.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ark_backup_failure_total", "legendFormat": "errors {{schedule}}" },
    { "expr": "ark_backup_success_total", "legendFormat": "success {{schedule}}" }
   ]
  },
  {
   "title": "Size of last backup per schedule",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ark_backup_tarball_size_bytes", "legendFormat": "{{schedule}}" }
   ]
  },
  { "title": "Go metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "GC duration [s]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{service=\"ark-metrics\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "open fds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{service=\"ark-metrics\"}",
     "legendFormat": " pod: {{pod}}"
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{service=\"ark-metrics\"}",
     "legendFormat": "bytes allocated ({{pod}})"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{service=\"ark-metrics\"}[30s])",
     "legendFormat": "alloc rate ({{pod}})"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{service=\"ark-metrics\"}",
     "legendFormat": "stack inuse ({{pod}})"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{service=\"ark-metrics\"}",
     "legendFormat": "heap inuse ({{pod}})"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{service=\"ark-metrics\"}",
     "legendFormat": "pod: {{pod}}"
    }
   ]
  }
 ]
}